baseURL = 'https://heyron.dev/'
defaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'HeyRon'
theme = 'dream'

[params]
  # Required for light/dark mode toggle
  lightTheme = "emerald"
  darkTheme = "forest"

  author = 'ron'
  description = 'A mind dump'
  avatar = 'img/avatar.jpg'
  headerTitle = 'heyron'
  motto = 'Writing and sharing thoughts'

  # Enable search
  enableSearch = true

  # Enable Giscus comments
  giscus = true

  # Social links
  [params.social]
    # github = 'DevEstacion'
    # twitter = '@ronskidude'
    # email = 'devestacion@gmail.com'

  # Navigation
  [params.navigation]
    home = true
    posts = true
    about = true
